# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4521a334f2d3ec18fb4182ab7f6cc6f6f2b3ae714d2fabac54cac6f6946e5f99b8a746e116f313a457aeebc2b3d723635fcfe80cf1bfb7319f19115a2da415

test:
  secret_key_base: b222becce448c98fb082a90ca84b5b5a936a25437b35eb86b16a406f278c4af4170bb317501fc13e287516d23bfc9507f35b5d68c177f70397fcef08080c321a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
